### ISSUE TITLE
Shutdown of deresute.info

### ISSUE THREAD

**Issue by Snack-X** [superk589/DereGuide#16]
As-is. It has shut down at the request of the original copyright holder.

**Comment by superk589** [comment]
I'm very sorry for hearing this. Maybe it's caused by 3D model viewer and CGSSGuide new version's promotion?
Can you share more information of the copyright holder request detail?

**Comment by CaiMiao** [comment]
Sad news.

**Comment by Snack-X** [comment]
I got legal letter from the legal representative. They demanded for the immediate termination of the website. They cited **everything** of the site as the copyright infringed material.

**Comment by suzutan** [comment]
sad news. :<

**Comment by CaiMiao** [comment]
@summertriangle-dev Did you receive any take down request ? Can we have jacket image on starlight_sync ?

**Comment by summertriangle-dev** [comment]
I haven't.

Jacket images are here:
https://hoshimoriuta.kirara.ca/jacket/[musicid].png

**Comment by superk589** [comment]
solve this by using jacket from hoshimoriuta and beatmap data from .bdb files.
