### ISSUE TITLE
关于可变BPM歌曲的谱面绘制问题

### ISSUE THREAD

**Issue by superk589** [superk589/DereGuide#2]
已知歌曲 参考https://deresute.info  
计划采用手工计算来解决此问题

**Comment by Snack-X** [comment]
So... my *thing* has closed, and I'm just dropping the informations here.
I don't understand Chinese, but I guess it means you need BPM change informations.

`liveid` means the pattern(beatmap) ID. Music ID and pattern ID is different, you know.
`start` means the start time of a pattern. It is usually the timestamp of the first note, but sometimes it is earlier than first note for various reasons. You don't have to take this, just add this to the BPM change timestamps.
And BPM change information lines follow. Left is timestamp, right is BPM value.

For example, HANAKANZASHI is marked as BPM 125, but it actually starts from BPM 90. Then after `10.52+2.666667` seconds, BPM changes into 125.

```
# 花簪 HANAKANZASHI
liveid=60
start=2.666667
0,90
10.52,125

# 気持ちいいよね 一等賞!
liveid=73
start=2.622951
0,183
19.672131,172
43.393061,130
56.316138,150
59.516138,165
62.425229,180
65.084529,183

# -LEGNE- 仇なす剣 光の旋律
liveid=24
start=2.8
0,150
9.7,189

# Trancing Pulse
# this one is not accurate
liveid=35
start=1.59292
0,113
18.318584,129
19.247788,149
20.857183,141
21.71748,143

# Snow Wings
liveid=55,509
start=2.25
0,160
12.75,167

# 命燃やして恋せよ乙女
liveid=321,531
start=3.333333
0,72
16.666666,112
```

**Comment by superk589** [comment]
Thank you very much for the information. I'll try this.

**Comment by suzutan** [comment]
@Snack-X Is it OK to ask a single question? Do you calculate variable BPM information from music score data? Or would you add information separately?

**Comment by superk589** [comment]
@Snack-X 
After using these data, i found that some beatmap notes are still not aligned to lines.
For example, in 気持ちいいよね 一等賞! between  62.425229,180 and 65.084529,183 seems that exists another range of other bpm. And 65.084529,183 seems not the finish of changing.
The same as suzutan says. I also want to know how to calculate this, can I calculate it myself?

**Comment by superk589** [comment]
It seems that 気持ちいいよね 一等賞 stops changing after 65.4142,183
But I'm still not sure between 62.425229,180 and 65.4142,183 how it changes.

**Comment by superk589** [comment]
I've added a file BpmShift.plist at CGSSGuide/Song/
If anyone have accurate data, send a pull request then.

**Comment by superk589** [comment]
Fixed and modified some timestamp info (especially for 気持ちいいよね 一等賞! and Trancing Pulse). 
More details in CGSSGuide/Song/BpmShift.plist
