### ISSUE TITLE
About DereGuide Sign in Dowloading and Loading

### ISSUE THREAD

**Issue by ShinoharaYuuyoru** [superk589/DereGuide#22]
I find that when DereGuide is downloading or loading, the DereGuide Sign(the triangle made by Cu, Co, Pa's shooting stars) is not spinning as a circle.
When every shooting star spins to the top of circle, Co is the highest, Cu takes the second place, and the Pa is the lowest.
I'll be appreciate if developers can discover this small problem.
Thank you!

**Comment by superk589** [comment]
Thank you for telling me the subtle but significant problem. It will be fixed next version.
