### ISSUE TITLE
Wrong name shown in home screen

### ISSUE THREAD

**Issue by tsekityam** [superk589/DereGuide#27]
![img_3884](https://user-images.githubusercontent.com/3814422/46348784-b6d10580-c682-11e8-83ec-573ab4320938.PNG)

I am using iOS12 on my iPhone 6 Plus, and the name of the app changed to `$(PRODUCT_NAME)` after the recent update.

I think we need to replace [all the instances](https://github.com/superk589/DereGuide/search?utf8=✓&q=%24%28PRODUCT_NAME%29&type=) of `$(PRODUCT_NAME)` with `DereGuide`

**Comment by superk589** [comment]
Thank you for this issue. Fixed.
