### ISSUE TITLE
切换回主界面时，下方的标签栏，图标会从错误的位置闪现回底部（ios12.1）

### ISSUE THREAD

**Issue by arbalest876** [superk589/DereGuide#29]
进入任意无下方标签栏的页面，如工具里的各个页面
之后点返回，回到主界面，下方的标签栏，5个图标会出现在相对偏左上一点的地方，然后闪现回到原来的地方（底部）
印象中是昨天升级了ios12.1之后才出现的，不过最近没怎么开，不排除是app新版本的问题。

**Comment by superk589** [comment]
这是一个苹果内部的 bug，不过我会尝试修复一下
